"""Remove imageUrl from notes

Revision ID: 0d54fd6929d5
Revises: aaa6d6b2ae41
Create Date: 2025-05-02 16:04:15.596363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d54fd6929d5'
down_revision: Union[str, None] = 'aaa6d6b2ae41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'imageUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
