"""Add users reference to notes

Revision ID: 8fe25770fe04
Revises: 0d54fd6929d5
Create Date: 2025-05-05 09:38:39.490979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe25770fe04'
down_revision: Union[str, None] = '0d54fd6929d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('userId', sa.Uuid(as_uuid=False), nullable=False))
    op.create_foreign_key(None, 'notes', 'users', ['userId'], ['id'])
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'userId')
    # ### end Alembic commands ###
